// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrzpfSmvvu71DI9f9vReiT0rZn26ivjvw',
    appId: '1:96198658949:android:02968f9aa48ab0eb6552ec',
    messagingSenderId: '96198658949',
    projectId: 'todolist-380af',
    storageBucket: 'todolist-380af.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0jixCCM17apLV04TPeVNY1TBiT0ATQhk',
    appId: '1:96198658949:ios:50286dac3ca2d5ec6552ec',
    messagingSenderId: '96198658949',
    projectId: 'todolist-380af',
    storageBucket: 'todolist-380af.firebasestorage.app',
    androidClientId: '96198658949-cuijec99hm86gfvcgufokhbcs4t2ammg.apps.googleusercontent.com',
    iosClientId: '96198658949-csu1rsl8cg3am46f0tpmvgnscgq8jh3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracker',
  );
}
